version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${GATEWAY_NODE_ENV:-development}
      DOTENV_KEY: ${GATEWAY_DOTENV_KEY}
    depends_on:
      - auth-service
      - navigation-service
    networks:
      - trafine-network

  # Service d'authentification
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: ${AUTH_NODE_ENV:-development}
      DOTENV_KEY: ${AUTH_DOTENV_KEY}
    depends_on:
      - mongodb
    networks:
      - trafine-network

  # Service de navigation
  navigation-service:
    build: ./navigation-service
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: ${NAV_NODE_ENV}
      DOTENV_KEY: ${NAV_DOTENV_KEY}
    depends_on:
      - postgres
    networks:
      - trafine-network

  # Web Client (Next.js)
  web-client:
    build: ./web-client
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - API_URL=http://api-gateway:3000

    depends_on:
      - api-gateway
    networks:
      - trafine-network

  # MongoDB pour le services d'authentification
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - trafine-network

  # PostgreSQL avec PostGIS pour les services de navigation et incidents
  postgres:
    image: postgis/postgis:14-3.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=trafine-navigation,trafine-incidents,trafine-analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/init-multiple-postgresql-databases.sh
    networks:
      - trafine-network

networks:
  trafine-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data: